package.json, src/components/ColorBox/HSVGradient.jsx, src/components/ColorBox/index.jsx, src/components/ColorButton.jsx, src/components/ColorInput.jsx, src/components/ColorPalette.jsx, src/components/ColorPicker.jsx, src/helpers/colorTool.js, src/helpers/commonTypes.js, test/ColorBox.test.js, test/ColorInput.test.js, test/ColorPalette.test.js, test/ColorPicker.test.js, test/colorTool.test.js
ColorButton, ColorInput, ColorPalette, ColorPicker
=> feat: coverage 100%

test/ColorBox.test.js
See : https://github.com/testing-library/react-testing-library/issues/268
=> fix: tests using pageX, pageY MouseEvent

README.md
{Please describe here the changes}
- nodejs / npm / yarn
=> NPM is added with install/i

src/types/types.d.ts
This add ts types to the component so typescirpt user can use it too.
=> Add ts types

.packito.json, package.json, src/types/index.d.ts
=> feat: done #43

src/helpers/colorTool.js, test/colorTool.test.js
=> fix: done #29

src/components/ColorBox/AlphaSlider.jsx, src/components/ColorBox/HSVGradient.jsx, src/components/ColorBox/HueSlider.jsx, src/components/ColorBox/index.jsx, src/components/ColorPalette.jsx, src/helpers/useEventCallback.js, test/ColorBox.test.js
=> feat: accessibility #46

src/components/ColorBox/index.jsx, src/components/ColorButton.jsx, src/components/ColorInput.jsx, src/components/ColorPalette.jsx, src/components/ColorPicker.jsx, src/helpers/colorTool.js, stories/ColorPicker.stories.js, test/colorTool.test.js
=> feat: disableApha #23

src/components/ColorBox/index.jsx, src/components/ColorInput.jsx, test/ColorBox.test.js
=> feat: colorbox error displayed once #30

.packito.json, index.d.ts, src/components/ColorPicker.jsx
=> fix: typescript d.ts was not ok

CONTRIBUTING.md, README.md, index.d.ts, stories/ColorPicker.stories.js, stories/intro.stories.mdx
=> chore: rename to material-ui-color

src/components/ColorBox/HSVGradient.jsx
=> fix: bug #70

src/types/index.d.ts
=> fix: typescript useTranslate export

package.json, src/components/ColorInput.jsx, src/components/ColorPicker.jsx, src/helpers/colorTool.js, src/types/index.d.ts, stories/ColorPicker.stories.js, test/ColorBox.test.js, test/ColorPicker.test.js, yarn.lock
=> feat: add disablePlainColor

src/components/ColorBox/index.jsx, src/components/ColorInput.jsx, src/components/ColorPicker.jsx, src/helpers/uncontrolled.js, test/ColorInput.test.js, test/ColorPicker.test.js
Fix issues on tests
- nodejs / npm / yarn
=> fix: onChange #100

src/components/ColorBox/index.jsx
Faulty display of Inputs
- nodejs / npm / yarn
=> fix: wrong margin for Inputs

src/components/ColorBox/HSVGradient.jsx, test/ColorBox.test.js
{Please describe here the changes}
=> fix: hsv gradient position is changed on slider drag

src/components/ColorBox/index.jsx
Regression for error message lineheight, since #113
- errors
=> Fix regression for error message lineheight (since #113, closes #122)

src/types/index.d.ts
=> fix: error in typing for colorpalette props

src/components/ColorButton.jsx
=> fix: colorButton checkered background alpha

src/components/ColorBox/index.jsx, src/components/ColorButton.jsx
=> feat: display incorrect color using border red in Colorbutton and Colorbox

src/index.js, src/types/index.d.ts
=> feat: add createColor func

package.json
=> chore: update peerDeps

src/components/ColorInput.jsx, src/components/ColorPicker.jsx
=> jss crossing className in production

stories/ColorPicker.stories.js
=> doc: remove translate in ColorPicker story

package.json, src/components/ColorInput.jsx, src/components/ColorPicker.jsx
#160 
add extensions js jsx to package script
=> fix: yarn lint
